# Generated by Django 4.1.6 on 2023-04-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_education_profile_alter_experience_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.profile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.profile'),
        ),
        migrations.AlterField(
            model_name='interests',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.profile'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.profile'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.profile'),
        ),
    ]
