# Generated by Django 4.1.6 on 2023-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_education_profile_alter_experience_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='college',
            new_name='college1',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='degree',
            new_name='college2',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='gpa',
            new_name='gpa1',
        ),
        migrations.AddField(
            model_name='education',
            name='degree1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='degree2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='gpa2',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
