# Generated by Django 4.1.6 on 2023-04-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_rename_college_education_college1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
