# Generated by Django 4.1.6 on 2023-04-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_profile_desc_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
